import { DictionaryEntry, Category } from './types';

export const DICTIONARY_DATA: DictionaryEntry[] = [
  // --- NUMBERS (1-10) ---
  { id: 'n1', indonesian: 'Satu', mee: 'Ena', category: Category.NUMBER, notes: '1' },
  { id: 'n2', indonesian: 'Dua', mee: 'Wiya', category: Category.NUMBER, notes: '2' },
  { id: 'n3', indonesian: 'Tiga', mee: 'Wido', category: Category.NUMBER, notes: '3' },
  { id: 'n4', indonesian: 'Empat', mee: 'Wii', category: Category.NUMBER, notes: '4' },
  { id: 'n5', indonesian: 'Lima', mee: 'Idibii', category: Category.NUMBER, notes: '5' },
  { id: 'n6', indonesian: 'Enam', mee: 'Benumi', category: Category.NUMBER, notes: '6' },
  { id: 'n7', indonesian: 'Tujuh', mee: 'Pituwo', category: Category.NUMBER, notes: '7' },
  { id: 'n8', indonesian: 'Delapan', mee: 'Waguwo', category: Category.NUMBER, notes: '8' },
  { id: 'n9', indonesian: 'Sembilan', mee: 'Iyee', category: Category.NUMBER, notes: '9' },
  { id: 'n10', indonesian: 'Sepuluh', mee: 'Gaati', category: Category.NUMBER, notes: '10' },

  // --- NUMBERS (11-19) ---
  { id: 'n11', indonesian: 'Sebelas', mee: 'Enamagati', category: Category.NUMBER, notes: '11' },
  { id: 'n12', indonesian: 'Dua belas', mee: 'Wiyamagati', category: Category.NUMBER, notes: '12' },
  { id: 'n13', indonesian: 'Tiga belas', mee: 'Widomagati', category: Category.NUMBER, notes: '13' },
  { id: 'n14', indonesian: 'Empat belas', mee: 'Wiimagati', category: Category.NUMBER, notes: '14' },
  { id: 'n15', indonesian: 'Lima belas', mee: 'Idibiimagati', category: Category.NUMBER, notes: '15' },
  { id: 'n16', indonesian: 'Enam belas', mee: 'Benumimagati', category: Category.NUMBER, notes: '16' },
  { id: 'n17', indonesian: 'Tujuh belas', mee: 'Pituwomagati', category: Category.NUMBER, notes: '17' },
  { id: 'n18', indonesian: 'Delapan belas', mee: 'Waguwomagati', category: Category.NUMBER, notes: '18' },
  { id: 'n19', indonesian: 'Sembilan belas', mee: 'Iyeegaati', category: Category.NUMBER, notes: '19' },

  // --- NUMBERS (20-29) ---
  { id: 'n20', indonesian: 'Dua puluh', mee: 'Mepina', category: Category.NUMBER, notes: '20' },
  { id: 'n21', indonesian: 'Dua puluh satu', mee: 'Enamamepina', category: Category.NUMBER, notes: '21' },
  { id: 'n22', indonesian: 'Dua puluh dua', mee: 'Wiyamamepina', category: Category.NUMBER, notes: '22' },
  { id: 'n23', indonesian: 'Dua puluh tiga', mee: 'Widomamepina', category: Category.NUMBER, notes: '23' },
  { id: 'n24', indonesian: 'Dua puluh empat', mee: 'Wiimamepina', category: Category.NUMBER, notes: '24' },
  { id: 'n25', indonesian: 'Dua puluh lima', mee: 'Idibimamepina', category: Category.NUMBER, notes: '25' },
  { id: 'n26', indonesian: 'Dua puluh enam', mee: 'Benumimamepina', category: Category.NUMBER, notes: '26' },
  { id: 'n27', indonesian: 'Dua puluh tujuh', mee: 'Pituwomamepina', category: Category.NUMBER, notes: '27' },
  { id: 'n28', indonesian: 'Dua puluh delapan', mee: 'Wagumamepina', category: Category.NUMBER, notes: '28' },
  { id: 'n29', indonesian: 'Dua puluh sembilan', mee: 'Iyeemepina', category: Category.NUMBER, notes: '29' },

  // --- NUMBERS (30-39) ---
  { id: 'n30', indonesian: 'Tiga puluh', mee: 'Yokagatii', category: Category.NUMBER, notes: '30' },
  { id: 'n31', indonesian: 'Tiga puluh satu', mee: 'Enamayokagati', category: Category.NUMBER, notes: '31' },
  { id: 'n32', indonesian: 'Tiga puluh dua', mee: 'Wiyamayokagati', category: Category.NUMBER, notes: '32' },
  { id: 'n33', indonesian: 'Tiga puluh tiga', mee: 'Widoomayokagati', category: Category.NUMBER, notes: '33' },
  { id: 'n34', indonesian: 'Tiga puluh empat', mee: 'Wiimayokagati', category: Category.NUMBER, notes: '34' },
  { id: 'n35', indonesian: 'Tiga puluh lima', mee: 'Idibima yokagati', category: Category.NUMBER, notes: '35' },
  { id: 'n36', indonesian: 'Tiga puluh enam', mee: 'Benumima yokagati', category: Category.NUMBER, notes: '36' },
  { id: 'n37', indonesian: 'Tiga puluh tujuh', mee: 'Pituwoma yokagati', category: Category.NUMBER, notes: '37' },
  { id: 'n38', indonesian: 'Tiga puluh delapan', mee: 'Waguma yokagati', category: Category.NUMBER, notes: '38' },
  { id: 'n39', indonesian: 'Tiga puluh sembilan', mee: 'Iyeeyokagatii', category: Category.NUMBER, notes: '39' },

  // --- NUMBERS (40-49) ---
  { id: 'n40', indonesian: 'Empat puluh', mee: 'Mepiya', category: Category.NUMBER, notes: '40' },
  { id: 'n41', indonesian: 'Empat puluh satu', mee: 'Enama mepiya', category: Category.NUMBER, notes: '41' },
  { id: 'n42', indonesian: 'Empat puluh dua', mee: 'Wiyama mepiya', category: Category.NUMBER, notes: '42' },
  { id: 'n43', indonesian: 'Empat puluh tiga', mee: 'Widoma mepiya', category: Category.NUMBER, notes: '43' },
  { id: 'n44', indonesian: 'Empat puluh empat', mee: 'Wiima mepiya', category: Category.NUMBER, notes: '44' },
  { id: 'n45', indonesian: 'Empat puluh lima', mee: 'Idibima mepiya', category: Category.NUMBER, notes: '45' },
  { id: 'n46', indonesian: 'Empat puluh enam', mee: 'Menumima mepiya', category: Category.NUMBER, notes: '46' },
  { id: 'n47', indonesian: 'Empat puluh tujuh', mee: 'Pituwoma mepiya', category: Category.NUMBER, notes: '47' },
  { id: 'n48', indonesian: 'Empat puluh delapan', mee: 'Waguwoma mepiya', category: Category.NUMBER, notes: '48' },
  { id: 'n49', indonesian: 'Empat puluh sembilan', mee: 'Iyema mepiya', category: Category.NUMBER, notes: '49' },

  // --- NUMBERS (50-59) ---
  { id: 'n50', indonesian: 'Lima puluh', mee: 'Gatibeu', category: Category.NUMBER, notes: '50' },
  { id: 'n51', indonesian: 'Lima puluh satu', mee: 'Enama gatibeu', category: Category.NUMBER, notes: '51' },
  { id: 'n52', indonesian: 'Lima puluh dua', mee: 'Wiyama gatibeuu', category: Category.NUMBER, notes: '52' },
  { id: 'n53', indonesian: 'Lima puluh tiga', mee: 'Widoma gatibeu', category: Category.NUMBER, notes: '53' },
  { id: 'n54', indonesian: 'Lima puluh empat', mee: 'Wiima gatibeu', category: Category.NUMBER, notes: '54' },
  { id: 'n55', indonesian: 'Lima puluh lima', mee: 'Idibima gatibeu', category: Category.NUMBER, notes: '55' },
  { id: 'n56', indonesian: 'Lima puluh enam', mee: 'Benumima gatibeu', category: Category.NUMBER, notes: '56' },
  { id: 'n57', indonesian: 'Lima puluh tujuh', mee: 'Pituma gatibeu', category: Category.NUMBER, notes: '57' },
  { id: 'n58', indonesian: 'Lima puluh delapan', mee: 'Waguma gatibeu', category: Category.NUMBER, notes: '58' },
  { id: 'n59', indonesian: 'Lima puluh sembilan', mee: 'Iyema gatibeu', category: Category.NUMBER, notes: '59' },

  // --- NUMBERS (60-69) ---
  { id: 'n60', indonesian: 'Enam puluh', mee: 'Mekabado', category: Category.NUMBER, notes: '60' },
  { id: 'n61', indonesian: 'Enam puluh satu', mee: 'Enama mekabado', category: Category.NUMBER, notes: '61' },
  { id: 'n62', indonesian: 'Enam puluh dua', mee: 'Wiyama mekabado', category: Category.NUMBER, notes: '62' },
  { id: 'n63', indonesian: 'Enam puluh tiga', mee: 'Widoma mekabado', category: Category.NUMBER, notes: '63' },
  { id: 'n64', indonesian: 'Enam puluh empat', mee: 'Wiima mekabado', category: Category.NUMBER, notes: '64' },
  { id: 'n65', indonesian: 'Enam puluh lima', mee: 'Idibima mekabado', category: Category.NUMBER, notes: '65' },
  { id: 'n66', indonesian: 'Enam puluh enam', mee: 'Menumima mekabado', category: Category.NUMBER, notes: '66' },
  { id: 'n67', indonesian: 'Enam puluh tujuh', mee: 'Pituwoma mekabado', category: Category.NUMBER, notes: '67' },
  { id: 'n68', indonesian: 'Enam puluh delapan', mee: 'Waguwoma mekabado', category: Category.NUMBER, notes: '68' },
  { id: 'n69', indonesian: 'Enam puluh sembilan', mee: 'Iyema mekabado', category: Category.NUMBER, notes: '69' },

  // --- NUMBERS (70-79) ---
  { id: 'n70', indonesian: 'Tujuh puluh', mee: 'Mekamiyodaimebado', category: Category.NUMBER, notes: '70' },
  { id: 'n71', indonesian: 'Tujuh puluh satu', mee: 'Enama miyodaimebado', category: Category.NUMBER, notes: '71' },
  { id: 'n72', indonesian: 'Tujuh puluh dua', mee: 'Wiyama miyodaimebado', category: Category.NUMBER, notes: '72' },
  { id: 'n73', indonesian: 'Tujuh puluh tiga', mee: 'Widoma miyodaimebado', category: Category.NUMBER, notes: '73' },
  { id: 'n74', indonesian: 'Tujuh puluh empat', mee: 'Wiima miyodaimebado', category: Category.NUMBER, notes: '74' },
  { id: 'n75', indonesian: 'Tujuh puluh lima', mee: 'Idibima miyodaimebado', category: Category.NUMBER, notes: '75' },
  { id: 'n76', indonesian: 'Tujuh puluh enam', mee: 'Benumima miyodaimebado', category: Category.NUMBER, notes: '76' },
  { id: 'n77', indonesian: 'Tujuh puluh tujuh', mee: 'Pituwoma miyodaimebado', category: Category.NUMBER, notes: '77' },
  { id: 'n78', indonesian: 'Tujuh puluh delapan', mee: 'Waguwoma miyodaimebado', category: Category.NUMBER, notes: '78' },
  { id: 'n79', indonesian: 'Tujuh puluh sembilan', mee: 'Iyemamiyodaimebado', category: Category.NUMBER, notes: '79' },

  // --- NUMBERS (100+) ---
  { id: 'n100', indonesian: 'Seratus', mee: 'Ogaikabado', category: Category.NUMBER, notes: '100' },
  { id: 'n101', indonesian: 'Seratus satu', mee: 'Ogaikabadoma ena', category: Category.NUMBER, notes: '101' },
  { id: 'n102', indonesian: 'Seratus dua', mee: 'Ogaikabadoma Wiya', category: Category.NUMBER, notes: '102' },
  { id: 'n103', indonesian: 'Seratus tiga', mee: 'Ogaikabadoma Wido', category: Category.NUMBER, notes: '103' },
  { id: 'n104', indonesian: 'Seratus empat', mee: 'Ogaikabadoma Wii', category: Category.NUMBER, notes: '104' },
  { id: 'n105', indonesian: 'Seratus lima', mee: 'Ogaikabadoma idibi', category: Category.NUMBER, notes: '105' },
  { id: 'n106', indonesian: 'Seratus enam', mee: 'Ogaikabadoma benumi', category: Category.NUMBER, notes: '106' },
  { id: 'n107', indonesian: 'Seratus tujuh', mee: 'Ogaikabadoma pituwo', category: Category.NUMBER, notes: '107' },
  { id: 'n108', indonesian: 'Seratus delapan', mee: 'Ogaikabadoma waguwo', category: Category.NUMBER, notes: '108' },
  { id: 'n109', indonesian: 'Seratus sembilan', mee: 'Ogaikabadoma iyee', category: Category.NUMBER, notes: '109' },
  { id: 'n110', indonesian: 'Seratus sepuluh', mee: 'Ogaikabadoma gatii', category: Category.NUMBER, notes: '110' },

  { id: 'n1000', indonesian: 'Seribu', mee: 'Gaatibeu', category: Category.NUMBER, notes: '1000' },
  { id: 'n5000', indonesian: 'Lima ribu', mee: 'Muto Idibii', category: Category.NUMBER, notes: '5000' },
  { id: 'n10000', indonesian: 'Sepuluh ribu', mee: 'Mutoo Gatii', category: Category.NUMBER, notes: '10000' },

  // --- PRONOUNS ---
  { id: 'p1', indonesian: 'Saya', mee: 'Anii', category: Category.PRONOUN },
  { id: 'p2', indonesian: 'Kamu', mee: 'Akii', category: Category.PRONOUN },
  { id: 'p3', indonesian: 'Kami', mee: 'Inii', category: Category.PRONOUN },
  { id: 'p4', indonesian: 'Kita', mee: 'Inii', category: Category.PRONOUN },
  { id: 'p5', indonesian: 'Dia', mee: 'Okai', category: Category.PRONOUN },
  { id: 'p6', indonesian: 'Mereka', mee: 'Okeii', category: Category.PRONOUN },
  { id: 'p7', indonesian: 'Itu', mee: 'iKou', category: Category.PRONOUN },
  { id: 'p8', indonesian: 'Ini', mee: 'kiii', category: Category.PRONOUN },

  // --- QUESTIONS ---
  { id: 'q1', indonesian: 'Apa', mee: 'Maagiyoo', category: Category.QUESTION },
  { id: 'q2', indonesian: 'Kapan', mee: 'Menaa', category: Category.QUESTION },
  { id: 'q3', indonesian: 'Dimana', mee: 'Kaiyaa', category: Category.QUESTION },
  { id: 'q4', indonesian: 'Yang mana', mee: 'Kawikaaki', category: Category.QUESTION },
  { id: 'q5', indonesian: 'Siapa', mee: 'Meime', category: Category.QUESTION },
  { id: 'q6', indonesian: 'Mengapa', mee: 'Maagiyokaa', category: Category.QUESTION },
  { id: 'q7', indonesian: 'Kenapa', mee: 'Maagiyokaa', category: Category.QUESTION },
  { id: 'q8', indonesian: 'Bagaimana', mee: 'Kadanii', category: Category.QUESTION },
  { id: 'q9', indonesian: 'Dari mana', mee: 'Kaiya Makee', category: Category.QUESTION },
  { id: 'q10', indonesian: 'Ke mana', mee: 'Kaya Uwetee', category: Category.QUESTION },
  { id: 'q11', indonesian: 'Berapa', mee: 'Magoo', category: Category.QUESTION },

  // --- COMMON WORDS ---
  { id: 'c1', indonesian: 'Iya', mee: 'Iii', category: Category.COMMON },
  { id: 'c2', indonesian: 'Tidak', mee: 'Beu', category: Category.COMMON },
  { id: 'c3', indonesian: 'Barangkali', mee: 'Ikoukeii Yuwa', category: Category.COMMON },
  { id: 'c4', indonesian: 'Mungkin', mee: 'Ikoukeii Yuwa', category: Category.COMMON },
  { id: 'c5', indonesian: 'Orang', mee: 'Mee', category: Category.COMMON },
  { id: 'c6', indonesian: 'Laki-laki', mee: 'Yame', category: Category.COMMON },
  { id: 'c7', indonesian: 'Perempuan', mee: 'Yagamo', category: Category.COMMON },
  { id: 'c8', indonesian: 'Nama', mee: 'Ekaa', category: Category.COMMON },
  { id: 'c9', indonesian: 'Uang', mee: 'Megee', category: Category.COMMON },
  { id: 'c10', indonesian: 'Kamar', mee: 'Baa Kaboo', category: Category.COMMON },
  { id: 'c11', indonesian: 'WC', mee: 'Baa Kaboo', category: Category.COMMON },
  { id: 'c12', indonesian: 'Air', mee: 'Uwoo', category: Category.COMMON },
  { id: 'c13', indonesian: 'Jalan', mee: 'Ita', category: Category.COMMON },
  { id: 'c14', indonesian: 'Kira-kira', mee: 'Yuwa', category: Category.COMMON },
  { id: 'c15', indonesian: 'Semua', mee: 'Idimaa', category: Category.COMMON },
  { id: 'c16', indonesian: 'Kalau', mee: 'Koudanite', category: Category.COMMON },
  { id: 'c17', indonesian: 'Jika', mee: 'Koudanite', category: Category.COMMON },
  { id: 'c18', indonesian: 'Lebih lagi', mee: 'Inooma', category: Category.COMMON },
  { id: 'c19', indonesian: 'Sekarang', mee: 'Itokou', category: Category.TIME },
  { id: 'c20', indonesian: 'Belum', mee: 'Beu', category: Category.COMMON },
  { id: 'c21', indonesian: 'Karena', mee: 'Kouya', category: Category.COMMON },
  { id: 'c22', indonesian: 'Tetapi', mee: 'Kodoya', category: Category.COMMON },
  { id: 'c23', indonesian: 'Di sini', mee: 'Kiiya', category: Category.COMMON },
  { id: 'c24', indonesian: 'Sama', mee: 'Enadani', category: Category.COMMON },
  { id: 'c25', indonesian: 'Punya', mee: 'Ewaa', category: Category.COMMON },
  { id: 'c26', indonesian: 'Ada', mee: 'Topa', category: Category.COMMON },
  { id: 'c27', indonesian: 'Bekas', mee: 'Dogaa', category: Category.COMMON },
  { id: 'c28', indonesian: 'Maaf', mee: 'Ipanayaikai', category: Category.COMMON },
  { id: 'c29', indonesian: 'Silakan', mee: 'Naaketiyawi', category: Category.COMMON },
  { id: 'c30', indonesian: 'Terimakasih', mee: 'Idee', category: Category.COMMON },
  { id: 'c31', indonesian: 'Selamat jalan', mee: 'Koya Uwiii', category: Category.COMMON },
  { id: 'c32', indonesian: 'Sarang', mee: 'Geka', category: Category.NATURE },
  { id: 'c33', indonesian: 'Gunung', mee: 'Diimi', category: Category.NATURE },
  { id: 'c34', indonesian: 'Tanjung', mee: 'Diimi pugaa', category: Category.NATURE },
  { id: 'c35', indonesian: 'Ekor', mee: 'Puga', category: Category.NATURE },
  { id: 'c36', indonesian: 'Angin', mee: 'Bou', category: Category.NATURE },
  { id: 'c37', indonesian: 'Hujan', mee: 'Edi', category: Category.NATURE },

  // --- ADJECTIVES ---
  { id: 'a1', indonesian: 'Baik', mee: 'Enaao', category: Category.ADJECTIVE },
  { id: 'a2', indonesian: 'Jelek', mee: 'Peu', category: Category.ADJECTIVE },
  { id: 'a3', indonesian: 'Betul', mee: 'Maakodo', category: Category.ADJECTIVE },
  { id: 'a4', indonesian: 'Benar', mee: 'Maakodo', category: Category.ADJECTIVE },
  { id: 'a5', indonesian: 'Indah', mee: 'Enauto', category: Category.ADJECTIVE },
  { id: 'a6', indonesian: 'Cantik', mee: 'Enauto', category: Category.ADJECTIVE },
  { id: 'a7', indonesian: 'Besar', mee: 'Ibo', category: Category.ADJECTIVE },
  { id: 'a8', indonesian: 'Kecil', mee: 'Daaba', category: Category.ADJECTIVE },
  { id: 'a9', indonesian: 'Banyak', mee: 'Uminaa', category: Category.ADJECTIVE },
  { id: 'a10', indonesian: 'Sedikit', mee: 'Wiyatoo', category: Category.ADJECTIVE },
  { id: 'a11', indonesian: 'Sangat sekali', mee: 'Makodo', category: Category.ADJECTIVE },
  { id: 'a12', indonesian: 'Bisa', mee: 'Keitimake', category: Category.ADJECTIVE },
  { id: 'a13', indonesian: 'Jauh', mee: 'Potoo', category: Category.ADJECTIVE },
  { id: 'a14', indonesian: 'Dekat', mee: 'Kapaa', category: Category.ADJECTIVE },
  { id: 'a15', indonesian: 'Kanan', mee: 'Etikatoo', category: Category.ADJECTIVE },
  { id: 'a16', indonesian: 'Kiri', mee: 'Akatoo', category: Category.ADJECTIVE },
  { id: 'a17', indonesian: 'Baru', mee: 'Iyaa', category: Category.ADJECTIVE },
  { id: 'a18', indonesian: 'Tua', mee: 'Adama', category: Category.ADJECTIVE },
  { id: 'a19', indonesian: 'Panjang', mee: 'Woyaa', category: Category.ADJECTIVE },
  { id: 'a20', indonesian: 'Pendek', mee: 'Pinii', category: Category.ADJECTIVE },
  { id: 'a21', indonesian: 'Murah', mee: 'Adeka Daba', category: Category.ADJECTIVE },
  { id: 'a22', indonesian: 'Mahal', mee: 'Adeka Ibo', category: Category.ADJECTIVE },
  { id: 'a23', indonesian: 'Panas', mee: 'Gobii', category: Category.ADJECTIVE },
  { id: 'a24', indonesian: 'Dingin', mee: 'Oo', category: Category.ADJECTIVE },
  { id: 'a25', indonesian: 'Lapar', mee: 'Igapu', category: Category.ADJECTIVE },
  { id: 'a26', indonesian: 'Bahagia', mee: 'Ideide', category: Category.ADJECTIVE },
  { id: 'a27', indonesian: 'Gembira', mee: 'Ideide', category: Category.ADJECTIVE },
  { id: 'a28', indonesian: 'Sakit', mee: 'Didii', category: Category.ADJECTIVE },
  { id: 'a29', indonesian: 'Mentah', mee: 'Epipode beu', category: Category.ADJECTIVE },
  { id: 'a30', indonesian: 'Gila', mee: 'Dimibeu', category: Category.ADJECTIVE },
  { id: 'a31', indonesian: 'Sakit kepala', mee: 'Dagi didi', category: Category.ADJECTIVE },
  { id: 'a32', indonesian: 'Sedih', mee: 'Kogaa', category: Category.ADJECTIVE },

  // --- VERBS ---
  { id: 'v1', indonesian: 'Jangan', mee: 'Tekeitai', category: Category.VERB },
  { id: 'v2', indonesian: 'Pergi', mee: 'Uwii', category: Category.VERB },
  { id: 'v3', indonesian: 'Datang', mee: 'Meii', category: Category.VERB },
  { id: 'v4', indonesian: 'Berjalan', mee: 'Ita Uwi', category: Category.VERB },
  { id: 'v5', indonesian: 'Bicara', mee: 'Manawegai', category: Category.VERB },
  { id: 'v6', indonesian: 'Hilang', mee: 'Igaii', category: Category.VERB },
  { id: 'v7', indonesian: 'Lihat', mee: 'Dou', category: Category.VERB },
  { id: 'v8', indonesian: 'Mengerti', mee: 'Gaai', category: Category.VERB },
  { id: 'v9', indonesian: 'Makan', mee: 'Naii', category: Category.VERB },
  { id: 'v10', indonesian: 'Minum', mee: 'Uwoo Nai', category: Category.VERB },
  { id: 'v11', indonesian: 'Dengar', mee: 'Yuwii', category: Category.VERB },
  { id: 'v12', indonesian: 'Tau', mee: 'Epi', category: Category.VERB },
  { id: 'v13', indonesian: 'Memberi', mee: 'Menii', category: Category.VERB },
  { id: 'v14', indonesian: 'Kasih', mee: 'Menii', category: Category.VERB },
  { id: 'v15', indonesian: 'Suka', mee: 'Ide', category: Category.VERB },
  { id: 'v16', indonesian: 'Mau', mee: 'Ide', category: Category.VERB },
  { id: 'v17', indonesian: 'Cinta', mee: 'Inai ide', category: Category.VERB },
  { id: 'v18', indonesian: 'Pikir', mee: 'Dimigai', category: Category.VERB },
  { id: 'v19', indonesian: 'Membuat', mee: 'Keitai', category: Category.VERB },
  { id: 'v20', indonesian: 'Tidur', mee: 'Uno Umii', category: Category.VERB },
  { id: 'v21', indonesian: 'Duduk', mee: 'Animakai', category: Category.VERB },
  { id: 'v22', indonesian: 'Potong', mee: 'Duwai', category: Category.VERB },
  { id: 'v23', indonesian: 'Beli', mee: 'Edai', category: Category.VERB },
  { id: 'v24', indonesian: 'Berhenti', mee: 'Ee Duwai', category: Category.VERB },
  { id: 'v25', indonesian: 'Muntah', mee: 'Edii', category: Category.VERB },
  { id: 'v26', indonesian: 'Ingat', mee: 'Gage', category: Category.VERB },
  { id: 'v27', indonesian: 'Kisah', mee: 'Tikaika keitita', category: Category.VERB },
  { id: 'v28', indonesian: 'Bawa', mee: 'Dokii', category: Category.VERB },

  // --- TIME ---
  { id: 't1', indonesian: 'Kemarin', mee: 'Geto', category: Category.TIME },
  { id: 't2', indonesian: 'Besok', mee: 'Aweeta', category: Category.TIME },
  { id: 't3', indonesian: 'Hari ini', mee: 'Ito Nago', category: Category.TIME },
  { id: 't4', indonesian: 'Pagi', mee: 'Abata', category: Category.TIME },
  { id: 't5', indonesian: 'Siang', mee: 'Agapi', category: Category.TIME },
  { id: 't6', indonesian: 'Malam', mee: 'Wanee', category: Category.TIME },
  { id: 't7', indonesian: 'Subuh', mee: 'Abata digi', category: Category.TIME },

  // --- FAMILY ---
  { id: 'f1', indonesian: 'Ayah', mee: 'Naitai', category: Category.FAMILY },
  { id: 'f2', indonesian: 'Ibu', mee: 'Noukai', category: Category.FAMILY },
  { id: 'f3', indonesian: 'Anak-anak', mee: 'Yokaidoo', category: Category.FAMILY },
  { id: 'f4', indonesian: 'Anak kecil', mee: 'Yoka dabaa', category: Category.FAMILY },
  { id: 'f5', indonesian: 'Om', mee: 'Naama', category: Category.FAMILY },
  { id: 'f6', indonesian: 'Paman', mee: 'Wenekame', category: Category.FAMILY },
  { id: 'f7', indonesian: 'Sepupu', mee: 'None', category: Category.FAMILY },
  { id: 'f8', indonesian: 'Tante', mee: 'Aniokaa', category: Category.FAMILY },
  { id: 'f9', indonesian: 'Bapak ade', mee: 'Naitai weneka', category: Category.FAMILY },
  { id: 'f10', indonesian: 'Bapak tua', mee: 'Naitai aikame', category: Category.FAMILY },
  { id: 'f11', indonesian: 'Adik kakak', mee: 'Inii keneka', category: Category.FAMILY },
  { id: 'f12', indonesian: 'Adik', mee: 'Anii weneka', category: Category.FAMILY },
  { id: 'f13', indonesian: 'Kakak laki-laki', mee: 'Nauwai', category: Category.FAMILY },
  { id: 'f14', indonesian: 'Kakak perempuan', mee: 'Anibai', category: Category.FAMILY },
  { id: 'f15', indonesian: 'Ipar', mee: 'Anigeka', category: Category.FAMILY },
  { id: 'f16', indonesian: 'Mertua', mee: 'Anibaka', category: Category.FAMILY },

  // --- LOCATION ---
  { id: 'l1', indonesian: 'Atas', mee: 'Wadou', category: Category.OTHER },
  { id: 'l2', indonesian: 'Bawah', mee: 'Miyou', category: Category.OTHER },
];
